spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/chat?createDatabaseIfNotExist=true
    username: springuser
    password: 8SYgSf&6<g]AVX=5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #generate_statistics: true
hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate:
    jdbc:
      batch_size: 50

server:
  address: 127.0.0.1
  port: 8443
  servlet:
    session:
      persistent: false
    context-path: /chat

#logging:
  #level:
    #org:
      #springframework:
      #  security: DEBUG
      #hibernate.SQL: DEBUG
      #hibernate.type: DEBUG
  #file: application.log
  #path: /etc/chatroom/logs
gmail:
  account: ychouaki.chatroom@gmail.com